application: binkscraper
version: 3-1-2
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /javascript
  static_dir: javascript

- url: /mapreduce(/.*)?
  script: libs/mapreduce/main.py
  login: admin

- url: /.*
  script: frontpage.py
  login: admin

libraries:
- name: lxml
  version: latest
- name: pycrypto
  version: latest
  
builtins:
- appstats: on
- remote_api: on