application: binkscraper
version: 5-1-0
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
  
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /mapreduce(/.*)?
  script: libs/GoogleAppEngineMapReduce-1.9.5.0/mapreduce/main.py
  login: admin

- url: /.*
  script: main.application
  login: admin

libraries:
- name: lxml
  version: latest
- name: pycrypto
  version: latest
  
builtins:
- appstats: on
- remote_api: on