#usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

TEAMS = {
# keys are pinnacle team names
# values are corresponding aliases
# value keys are wettpoint team ids if they exist
    'Baseball' : {
        'MLB Spring Training' : 'MLB Regular Season',
        'MLB Regular Season' : {
            'keys' : {
                     'Baltimore Orioles'         : '01',
                     'Boston Red Sox'            : '02',
                     'Chicago White Sox'         : '03',
                     'Cleveland Indians'         : '04',
                     'Detroit Tigers'            : '05',
                     'Houston Astros'            : '06',
                     'Kansas City Royals'        : '07',
                     'LAA Angels'                : '08',
                     'Minnesota Twins'           : '09',
                     'New York Yankees'          : '10',
                     'Oakland Athletics'         : '11',
                     'Seattle Mariners'          : '12',
                     'Tampa Bay Rays'            : '13',
                     'Texas Rangers'             : '14',
                     'Toronto Blue Jays'         : '15',
                     'Arizona Diamondbacks'      : '16',
                     'Atlanta Braves'            : '17',
                     'Chicago Cubs'              : '18',
                     'Cincinnati Reds'           : '19',
                     'Colorado Rockies'          : '20',
                     'Los Angeles Dodgers'       : '21',
                     'Miami Marlins'             : '22',
                     'Milwaukee Brewers'         : '23',
                     'New York Mets'             : '24',
                     'Philadelphia Phillies'     : '25',
                     'Pittsburgh Pirates'        : '26',
                     'San Diego Padres'          : '27',
                     'San Francisco Giants'      : '28',
                     'St. Louis Cardinals'       : '29',
                     'Washington Nationals'      : '30',
                },
            'values' : {
                     '01' :         ['BAL ORIOLES'],
                     '02' :         ['BOS RED SOX'],
                     '03' :         ['CHI WHITE SOX'],
                     '04' :         ['CLE INDIANS'],
                     '05' :         ['DET TIGERS'],
                     '06' :         ['HOU ASTROS'],
                     '07' :         ['KC ROYALS'],
                     '08' :         ['Los Angeles Angels', 'ANA ANGELS'],
                     '09' :         ['MIN TWINS'],
                     '10' :         ['NY YANKEES'],
                     '11' :         ['OAK ATHLETICS'],
                     '12' :         ['SEA MARINERS'],
                     '13' :         ['TB RAYS'],
                     '14' :         ['TEX RANGERS'],
                     '15' :         ['TOR BLUE JAYS'],
                     '16' :         ['ARI DIAMONDBACKS'],
                     '17' :         ['ATL BRAVES'],
                     '18' :         ['CHI CUBS'],
                     '19' :         ['CIN REDS'],
                     '20' :         ['COL ROCKIES'],
                     '21' :         ['LA DODGERS'],
                     '22' :         ['MIA MARLINS'],
                     '23' :         ['MIL BREWERS'],
                     '24' :         ['NY METS'],
                     '25' :         ['PHI PHILLIES'],
                     '26' :         ['PIT PIRATES'],
                     '27' :         ['SD PADRES'],
                     '28' :         ['SF GIANTS'],
                     '29' :         ['STL CARDINALS'],
                     '30' :         ['WAS NATIONALS'],
                },
        },
    },
    'Soccer' : {
        'MLS Regular Season' : {
            'keys' : {
                      'Chicago Fire'            : '76602',
                      'Columbus Crew'           : '76603',
                      'D.C. United'             : '76607',
                      'Houston Dynamo'          : '119742',
                      'New England Revolution'  : '76601',
                      'New York Red Bulls'      : '76605',
                      'Montreal Impact'         : '148693',
                      'Philadelphia Union'      : '224216',
                      'Sporting Kansas City'    : '76606',
                      'Toronto FC'              : '146416',
                      'Deportivo Chivas USA'    : '100985',
                      'Colorado Rapids'         : '76608',
                      'FC Dallas'               : '76600',
                      'LA Galaxy'               : '76604',
                      'Portland Timbers'        : '148694',
                      'Real Salt Lake'          : '100984',
                      'San Jose Earthquakes'    : '76609',
                      'Seattle Sounders FC'     : '148697',
                      'Vancouver Whitecaps'     : '148696',
            },
            'values' : {
                        '76607'                 : ['DC United'],
                        '76601'                 : ['NEW ENG. REVOLUTION'],
                        '100985'                : ['Chivas USA'],
                        '76604'                 : ['Los Angeles Galaxy'],
                        '148697'                : ['Seattle Sounders'],
            },
        },
        'Bundesliga' : {
            'keys' : {
                      'Bayern Munchen'          : '809',
                      'Borussia Dortmund'       : '810',
                      'Schalke 04'              : '821',
                      'Bayer Leverkusen'        : '808',
                      'VfL Wolfsburg'           : '824',
                      'Borussia Monchengladbach': '811',
                      'FSV Mainz 05'            : '1900',
                      'Augsburg'                : '16732',
                      'TSG Hoffenheim'          : '16740',
                      'Hannover 96'             : '1895',
                      'Hertha Berlin'           : '819',
                      'Werder Bremen'           : '823',
                      'Eintracht Frankfurt'     : '1888',
                      'SC Freiburg'             : '816',
                      'VfB Stuttgart'           : '822',
                      'Hamburger SV'            : '817',
                      'Koln'                    : '813',
                      'SC Paderborn 07'         : '16722',
            },
            'values' : {
                        '809'                   : ['Bayern München', 'BAYERN MUNICH'],
                        '821'                   : ['FC SCHALKE 04'],
                        '811'                   : ['Borussia Mönchengladbach', 'BOR. MONCHENGLADBACH'],
                        '1900'                  : ['FSV Mainz'],
                        '16732'                 : ['FC Augsburg'],
                        '16740'                 : ['TSG 1899 Hoffenheim', '1899 HOFFENHEIM'],
                        '816'                   : ['Sport-Club Freiburg'],
                        '813'                   : ['FC Köln', 'FC KOLN'],
            },
        },
        'Premier League' : {
            'keys' : {
                      'Arsenal'             : '3',
                      'Aston Villa'         : '18',
                      'Burnley'             : '978',
                      'Chelsea'             : '4',
                      'Crystal Palace'      : '981',
                      'Everton'             : '12',
                      'Hull City'           : '1030',
                      'Leicester City'      : '13',
                      'Liverpool'           : '19',
                      'Manchester City'     : '984',
                      'Manchester United'   : '22',
                      'Newcastle United'    : '8',
                      'Queens Park Rangers' : '1015',
                      'Southampton'         : '15',
                      'Stoke City'          : '1017',
                      'Sunderland'          : '14',
                      'Swansea City'        : '1044',
                      'Tottenham Hotspur'   : '21',
                      'W.B.A'               : '996',
                      'West Ham United'     : '11',
            },
            'values' : {
                        '13'    : ['LEICESTER'],
                        '21'    : ['TOTTENHAM'],
                        '1044'  : ['SWANSEA'],
                        '22'    : ['MANCHESTER UTD'],
                        '8'     : ['NEWCASTLE'],
                        '1015'  : ['QPR'],
                        '996'   : ['West Bromwich Albion', 'WEST BROM'],
                        '11'    : ['WEST HAM'],
            },
        },
        'La Liga' : {
            'keys' : {
                      'Almeria'             : '14925',
                      'Athletic Bilbao'     : '746',
                      'Atletico Madrid'     : '1668',
                      'Barcelona'           : '747',
                      'Celta Vigo'          : '748',
                      'Cordoba'             : '1670',
                      'Deportivo La Coruna' : '749',
                      'Eibar'               : '1679',
                      'Elche'               : '1683',
                      'Getafe'              : '14923',
                      'Granada'             : '158258',
                      'Levante'             : '1667',
                      'Malaga'              : '752',
                      'Rayo Vallecano'      : '755',
                      'RCD Espanyol'        : '750',
                      'Real Madrid'         : '757',
                      'Real Sociedad'       : '758',
                      'Sevilla'             : '761',
                      'Valencia'            : '763',
                      'Villarreal'          : '764',
            },
            'values' : {
                        '14925' : ['Almería'],
                        '746'   : ['ATHLETIC CLUB'],
                        '1668'  : ['Atlético Madrid', 'ATL. MADRID'],
                        '747'   : ['FC Barcelona'],
                        '748'   : ['Celta'],
                        '1670'  : ['Córdoba'],
                        '749'   : ['Deportivo La Coruña', 'DEP. LA CORUNA'],
                        '158258': ['GRANADA CF'],
                        '752'   : ['Málaga'],
                        '750'   : ['Espanyol'],
            },
        },
        'Serie A' : {
            'keys' : {
                      'AC Milan'            : '728',
                      'AS Roma'             : '732',
                      'Atalanta'            : '719',
                      'Cagliari'            : '1049',
                      'Cesena'              : '83359',
                      'Chievo'              : '722',
                      'Empoli'              : '1055',
                      'Fiorentina'          : '723',
                      'Genoa'               : '1057',
                      'Hellas Verona'       : '736',
                      'Inter Milan'         : '724',
                      'Juventus'            : '725',
                      'Lazio'               : '726',
                      'Napoli'              : '1058',
                      'Palermo'             : '1056',
                      'Parma'               : '729',
                      'Sampdoria'           : '1062',
                      'Sassuolo'            : '134312',
                      'Torino'              : '733',
                      'Udinese'             : '734',
            },
            'values' : {
                        '732'   : ['ROMA'],
                        '724'   : ['Inter'],
                        '736'   : ['VERONA'],
            },
        },
    },
    'Handball' : {
        'Handball Bundesliga' : {
            'keys' : {
                      'SG Flensburg-Handewitt'  : '6608',
                      'Frisch auf Goppingen'    : '6614',
                      'VfL Gummersbach'         : '6621',
                      'HSV Hamburg'             : '23447',
                      'THW Kiel'                : '6607',
                      'Rhein-Neckar Lowen'      : '158007',
                      'TBV Lemgo'               : '6606',
                      'TuS N-Lubbecke'          : '23448',
                      'SC Magdeburg'            : '6609',
                      'MT Melsungen'            : '106062',
                      'HSG Wetzlar'             : '6617',
                      'Fuchse Berlin'           : '158008',
                      'TSV Hannover-Burgdorf'   : '207688',
                      'HBW Balingen-Weilstetten': '132814',
                      'SG BBM Bietigheim'       : '215171',
                      'TSG Friesenheim'         : '215159',
                      'Bergischer HC'           : '215165',
                      'HC Erlangen'             : '215169',
                      'TSV GWD Minden'          : '6613',
            },
            'values' : {
                        '6608'                  : ['Flensburg-Handewitt'],
                        '6614'                  : ['FA Göppingen', 'FA Goppingen'],
                        '6621'                  : ['Gummersbach'],
                        '23447'                 : ['Hamburg'],
                        '6607'                  : ['Kiel'],
                        '158007'                : ['Rhein-Neckar Löwen', 'Rhein-Neckar-Löwen'],
                        '6606'                  : ['Lemgo'],
                        '23448'                 : ['TuS N-Lübbecke', 'TuS-N-Lubbecke', 'N-Lubbecke'],
                        '6609'                  : ['Magdeburg'],
                        '6617'                  : ['Wetzlar'],
                        '158008'                : ['Füchse Berlin'],
                        '132814'                : ['HBW Balingen/Weilstetten', 'Balingen-Weilsteten', 'Balingen/Weilstetten'],
                        '215171'                : ['BBM Bietigheim'],
                        '215159'                : ['TSG Lu.-Friesenheim', 'TSG Ludwigshafen-Friesenheim'],
                        '215169'                : ['Erlangen'],
                        '6613'                  : ['GWD Minden', 'Minden-Hannover', 'Minden'],
            },
        },
    },
    'Football' : {
        'NFL' : {
            'keys' : {
                      'Arizona Cardinals'       : '01',
                      'Atlanta Falcons'         : '02',
                      'Baltimore Ravens'        : '03',
                      'Buffalo Bills'           : '04',
                      'Carolina Panthers'       : '05',
                      'Chicago Bears'           : '06',
                      'Cincinnati Bengals'      : '07',
                      'Cleveland Browns'        : '08',
                      'Dallas Cowboys'          : '09',
                      'Denver Broncos'          : '10',
                      'Detroit Lions'           : '11',
                      'Green Bay Packers'       : '12',
                      'Houston Texans'          : '13',
                      'Indianapolis Colts'      : '14',
                      'Jacksonville Jaguars'    : '15',
                      'Kansas City Chiefs'      : '16',
                      'Miami Dolphins'          : '17',
                      'Minnesota Vikings'       : '18',
                      'New England Patriots'    : '19',
                      'New Orleans Saints'      : '20',
                      'New York Giants'         : '21',
                      'New York Jets'           : '22',
                      'Oakland Raiders'         : '23',
                      'Philadelphia Eagles'     : '24',
                      'Pittsburgh Steelers'     : '25',
                      'San Diego Chargers'      : '26',
                      'San Francisco 49ers'     : '27',
                      'Seattle Seahawks'        : '28',
                      'St. Louis Rams'          : '29',
                      'Tampa Bay Buccaneers'    : '30',
                      'Tennessee Titans'        : '31',
                      'Washington Redskins'     : '32',
            },
            'values' : {
                        '01'                    : ['ARI CARDINALS'],
                        '02'                    : ['ATL FALCONS'],
                        '03'                    : ['BAL RAVENS'],
                        '04'                    : ['BUF BILLS'],
                        '05'                    : ['CAR PANTHERS'],
                        '06'                    : ['CHI BEARS'],
                        '07'                    : ['CIN BENGALS'],
                        '08'                    : ['CLE BROWNS'],
                        '09'                    : ['DAL COWBOYS'],
                        '10'                    : ['DEN BRONCOS'],
                        '11'                    : ['DET LIONS'],
                        '12'                    : ['GB PACKERS'],
                        '13'                    : ['HOU TEXANS'],
                        '14'                    : ['IND COLTS'],
                        '15'                    : ['JAC JAGUARS'],
                        '16'                    : ['KC CHIEFS'],
                        '17'                    : ['MIA DOLPHINS'],
                        '18'                    : ['MIN VIKINGS'],
                        '19'                    : ['NE PATRIOTS'],
                        '20'                    : ['NO SAINTS'],
                        '21'                    : ['NY GIANTS'],
                        '22'                    : ['NY JETS'],
                        '23'                    : ['OAK RAIDERS'],
                        '24'                    : ['PHI EAGLES'],
                        '25'                    : ['PIT PIRATES'],
                        '26'                    : ['SD CHARGERS'],
                        '27'                    : ['SF 49ers'],
                        '28'                    : ['SEA SEAHAWKS'],
                        '29'                    : ['STL RAMS'],
                        '30'                    : ['TB BUCCANEERS'],
                        '31'                    : ['TEN TITANS'],
                        '32'                    : ['WAS REDSKINS'],
            },
        },
    },
    'Hockey' : {
        'KHL' : {
            'keys' : {
                      # Bobrov divison
                      'Atlant'                      : '174550',
                      'Dinamo Minsk'                : '174553',
                      'Dinamo Riga'                 : '174549',
                      'Jokerit'                     : '4649',
                      'Medvescak Zagreb'            : '205839', #change datatstore
                      'SKA St Petersburg'           : '99847',
                      'Slovan Bratislava'           : '134210',
                      # Tarasov division
                      'Vityaz Chehov'               : '106361',
                      'Dynamo Moscow'               : '99836',
                      'Lokomotiv Yaroslavl'         : '99840',
                      'Severstal Cherepovec'        : '99842',
                      'Torpedo NN'                  : '152909',
                      'HC Sochi'                    : '324041',
                      'CSKA Moscow'                 : '99846',
                      # Kharlamov division
                      'Avtomobilist'                : '174552',
                      'Ak Bars Kazan'               : '99839',
                      'Lada Togliatti'              : '99837',
                      'Metallurg Magnitogorsk'      : '99838',
                      'Neftekhimik Nizhnekamsk'     : '99843',
                      'Traktor Chelyabinsk'         : '132276', # change datastore
                      'Yugra'                       : '216748',
                      # Chernyshev division
                      'Avangard Omsk'               : '99844',
                      'Admiral'                     : '300725',
                      'Amur Khabarovsk'             : '132277',
                      'Barys Astana'                : '174551',
                      'Metallurg Novokuznetsk'      : '99841',
                      'Salavat Ufa'                 : '99848',
                      'Sibir Novosibirsk'           : '99850',
            },
            'values' : {
                        # Bobrov divison
                        '174550'    : ['Atlant Mytischi', 'ATLANT MSK.'],
                        '174553'    : ['Dynamo Minsk', 'DINAMO MN.'],
                        '174549'    : ['Dynamo Riga', 'DINAMO R.'],
                        '205839'    : ['KHL Medvescak Zagreb', 'KHL MEDVESCAK Z.', 'KHL Medvescak'],
                        '99847'     : ['SKA St. Petersburg', 'SKA S.PETERSBURG'],
                        '134210'    : ['HC Slovan Bratislava', 'HC SL. BRATISLAVA'],
                        # Tarasov division
                        '106361'    : ['Vityaz Podolsk Chekhov', 'VITYAZ'],
                        '99836'     : ['Dynamo Moskva', 'DYNAMO MSK.'],
                        '99840'     : ['LOKOMOTIV'],
                        '99842'     : ['Severstal Cherepovets', 'SEVERSTAL'],
                        '152909'    : ['Torpedo Novgorod', 'TORPEDO'],
                        '99846'     : ['CSKA Moskva', 'CSKA MSK.'],
                        # Kharlamov division
                        '174552'    : ['Avtomobilist Yekaterinburg', 'AVTOMOBILIST EK.'],
                        '99839'     : ['AK BARS'],
                        '99837'     : ['LADA T.'],
                        '99838'     : ['METALLURG MG'],
                        '99843'     : ['NEFTEKHIMIK'],
                        '132276'    : ['Traktor Chel', 'TRAKTOR', 'Tractor'],
                        '216748'    : ['Yugra Khanty-Mansiysk', 'HC YUGRA', 'Ugra', 'HC Ugra'],
                        # Chernyshev division
                        '99844'     : ['AVANGARD'],
                        '300725'    : ['Admiral Vladivostok', 'ADMIRAL VL.'],
                        '132277'    : ['HC Amur', 'AMUR'],
                        '174551'    : ['BARYS A.'],
                        '99841'     : ['METALLURG NK'],
                        '99848'     : ['Salavat Yulaev Ufa', 'SALAVAT Y.'],
                        '99850'     : ['SIBIR N.'],
            },
        },
    },
}